apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  labels:
    app: javawebapp
  namespace: flipkart-ns
spec:
  containers:
  - name: javawebappcontainer
    image: hanifdockerrepo/java-web-app:1
    ports:
    - containerPort: 8080
    
