name: Validate YAML Files on Pull Request

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate_yaml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Validate YAML
      run: |
        sudo apt-get update
        sudo apt-get install -y yamllint
        yamllint . # replace with the directory containing your YAML files
