name: Validate-YAML

on:
  push:
    branches: [ main, uat ]
  pull_request:
    branches: [ main, uat ]
    types: [opened, edited, reopened]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML file
        run: yamllint **/*.yaml
      - name: Validate YAML file
        run: yamllint *.yaml
