name: Validate-YAML

on:
  push:
    branches: [validate]
    paths-ignore:
    - '.github/workflows/validate all yaml files.yaml'
  pull_request:
    branches: [main]
    types: [opened, edited, reopened]
    paths-ignore:
    - '.github/workflows/validate all yaml files.yaml'

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Validate YAML file
#       run: yamllint **/*.yaml
#      - name: Validate YAML file
#       run: yamllint *.yaml
      - name: Validate all files
        run: find . -type d -print0 | xargs -0 -I{} sh -c 'cd {}/ && yamllint . --no-warnings'
