name: Validate-YAML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, edited, reopened, synchronize ]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Validate YAML file
#        run: yamllint ./**/*.yaml --no-warnings
#      - name: Validate YAML file
#        run: yamllint *.yaml --no-warnings
      - name: Validate all files 
        run: find . -type d -print0 | xargs -0 -I{} sh -c 'echo {}/ && cd {}/ && yamllint . --no-warnings'
